name: Build and Minify Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build and minify
      run: |
        mkdir dist
        npm run build
    
    - name: Upload dist folder
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: dist/
